# Generated by Django 5.1.4 on 2025-06-20 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clientManagement", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaignpost",
            name="content",
        ),
    ]
