# Generated by Django 5.1.4 on 2025-06-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientManagement", "0002_remove_campaignpost_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignpost",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
